version: "3.8"

services: 
  mysql:
    image: 'mysql:5.7'
    env_file: 
      - ./env/mysql.env
    ports: 
      - '3307:3306'
    volumes:
      - ./mysql-dump/:/docker-entrypoint-initdb.d
  node:
    build: ./.
    env_file: 
      - ./env/mysql.env
    volumes: 
      - ./dist:/app
      - /app/node_modules
    ports: 
      - '3000:8080'
    depends_on: 
      - mysql

    